name: Build and Release Marlin

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  build-marlin:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio oficial de Marlin
    - name: Checkout Marlin Source
      run: |
        git clone --branch bugfix-2.1.x --depth 1 https://github.com/MarlinFirmware/Marlin.git marlin-source

    # Paso 2: Configurar el entorno
    - name: Setup Build Environment
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip gcc-avr avr-libc

    # Paso 3: Generar un archivo de prueba para verificar la subida
    - name: Create Test File
      run: |
        mkdir -p marlin-source/build/
        echo "Este es un archivo de prueba." > marlin-source/build/test.txt

    # Paso 4: Subir los archivos como artefactos
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Test-Artifacts
        path: marlin-source/build/
